# Solar Data Collection Configuration

general:
  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_level: INFO

  # Timezone for timestamp formatting
  timezone: America/New_York

  # Time ranges for queries
  hours_back: 24
  days_back: 30

  # Polling intervals (in seconds)
  poll_interval: 300
  retry_interval: 60

influxdb:
  # InfluxDB connection details
  url: https://your-influxdb-server:8086
  org: your-organization
  token: your-influx-token
  bucket: home_assistant/autogen
  verify_ssl: false

webhook:
  # Webhook destination
  url: https://your-webhook-endpoint.com

queries:
  # Flux query templates - use {bucket}, {start_time}, and {end_time} as placeholders
  power_query: |
    from(bucket: "{bucket}")
      |> range(start: {start_time}, stop: {end_time})
      |> filter(fn: (r) => r["entity_id"] == "whatever")
      |> filter(fn: (r) => r["_measurement"] == "kW")

  energy_query: |
    from(bucket: "{bucket}")
      |> range(start: {start_time}, stop: {end_time})
      |> filter(fn: (r) => r["_measurement"] == "kW")
      |> filter(fn: (r) => r["entity_id"] == "whatever")
      |> filter(fn: (r) => r["domain"] == "sensor")
      |> filter(fn: (r) => r["_field"] == "value")
      |> aggregateWindow(every: 1d, fn: integral, createEmpty: false)
      |> map(fn: (r) => ({ r with _value: r._value / 3600.0 }))

charts:
  # Chart display settings
  power_chart_title: Solar Power Data
  power_chart_units: kW
  energy_chart_title: Daily Solar Energy
  energy_chart_units: kWh

  # Display names for entities
  display_names:
    bellmore_solar_power: Solar Power
    bellmore_grid_power: Grid Power
    bellmore_home_power: Home Power