name: Weather Data Collection

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weather collection script
      env:
        AMBIENT_API_KEY: ${{ secrets.AMBIENT_API_KEY }}
        AMBIENT_APPLICATION_KEY: ${{ secrets.AMBIENT_APPLICATION_KEY }}
        TIMEZONE: ${{ secrets.TIMEZONE }}
        WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
      run: python ambient_claude_trmnl.py